#! /usr/bin/env python3

#
# Devuelve intercaz e IP
# IMPORTANTE: Necesita netifaces (pip install netifaces)
#
#

from netifaces import interfaces, ifaddresses, AF_INET

def ip4_addresses():
    ip_list = []
    for interface in interfaces():
        if AF_INET in ifaddresses(interface):
          for link in ifaddresses(interface)[AF_INET]:
              ip_list.append(interface+": "+link['addr'])
    return ip_list


if __name__ == "__main__":
    for add in ip4_addresses():
      print(add)
